services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: purplecaffeine
      POSTGRES_USER: purplecaffeine
      POSTGRES_PASSWORD: purplecaffeinepassword
    ports:
      - 5432:5432
    networks:
      - safe-tier
    restart:
      always
networks:
  safe-tier:
