"""Initial migration."""
# Generated by Django 4.2.1 on 2023-05-12 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration"""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=255
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("metrics", models.JSONField(default=list)),
                ("parameters", models.JSONField(default=list)),
                ("circuits", models.JSONField(default=list)),
                ("backend", models.JSONField(default=list)),
                ("operators", models.JSONField(default=list)),
                ("artifacts", models.JSONField(default=list)),
                ("texts", models.JSONField(default=list)),
                ("arrays", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
            ],
        ),
    ]
